
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Toolkit;
import java.io.IOException;
import static java.lang.Math.E;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Maxwell Maragia
 */
public class subjects extends javax.swing.JFrame {

    /**
     * Creates new form subjects
     */
    
    
        
    
    
        

    public subjects() throws IOException {
      
        initComponents();
       
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle(BaseClass.title());
        initComponents();
        
        //get filter subjects
        String filter=BaseClass.readFile("sare_hizo.txt");
        filter = filter.toString().trim();
        
        if(filter.equals("none")){
            String subjects[];
        }
        
        String [] filterArray=filter.split(",");
        if(filterArray.length > 0){
        
            List<String> list = Arrays.asList(filterArray);
            System.out.println(list);
            
            if(list.contains("bid all")){
                System.out.println("all is there");
            }
        }
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * "c_bidAll","c_art","c_computerScience","c_engineering","c_healthCare","c_humanities","c_marketing","c_naturalScience","c_politicalScience","c_businessManagement","c_economics","c_englishLiterature","c_socialSciences","c_psychology","c_philosophy","c_mathematicsStatistics","c_law","c_history","c_religion","c_other"
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox5 = new javax.swing.JCheckBox();
        scroller = new javax.swing.JScrollPane();
        subjects = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        c_bidAll = new javax.swing.JCheckBox();
        c_art = new javax.swing.JCheckBox();
        c_computerScience = new javax.swing.JCheckBox();
        c_engineering = new javax.swing.JCheckBox();
        c_healthCare = new javax.swing.JCheckBox();
        c_humanities = new javax.swing.JCheckBox();
        c_marketing = new javax.swing.JCheckBox();
        c_naturalScience = new javax.swing.JCheckBox();
        c_politicalScience = new javax.swing.JCheckBox();
        c_businessManagement = new javax.swing.JCheckBox();
        c_economics = new javax.swing.JCheckBox();
        c_englishLiterature = new javax.swing.JCheckBox();
        c_socialSciences = new javax.swing.JCheckBox();
        c_psychology = new javax.swing.JCheckBox();
        c_philosophy = new javax.swing.JCheckBox();
        c_mathematicsStatistics = new javax.swing.JCheckBox();
        c_law = new javax.swing.JCheckBox();
        c_history = new javax.swing.JCheckBox();
        c_religion = new javax.swing.JCheckBox();
        c_other = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jCheckBox5.setText("Health Care and life sciences");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        subjects.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Art", "Computer science", "Engineering", "Health Care and life sciences", "Humanities", "Marketing", "Natural science", "Political science", "Religion/ Theology", "Business and Management", "Economics", "English and Literature", "History", "Law", "Mathematics and Statistics", "Philosophy", "Psychology and Education", "Social Sciences" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scroller.setViewportView(subjects);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        c_bidAll.setText("Bid all");
        c_bidAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c_bidAllMouseClicked(evt);
            }
        });
        c_bidAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_bidAllActionPerformed(evt);
            }
        });

        c_art.setText("Art");
        c_art.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                c_artMouseMoved(evt);
            }
        });

        c_computerScience.setText("Computer science");

        c_engineering.setText("Engineering");

        c_healthCare.setText("Health Care and Life Sciences");

        c_humanities.setText("Humanities");

        c_marketing.setText("Marketing");

        c_naturalScience.setText("Natural science");

        c_politicalScience.setText("Political science");

        c_businessManagement.setText("Business and Management");

        c_economics.setText("Economics");

        c_englishLiterature.setText("English and Literature");

        c_socialSciences.setText("Social Sciences");

        c_psychology.setText("Psychology and Education");

        c_philosophy.setText("Philosophy");

        c_mathematicsStatistics.setText("Mathematics and Statistics");

        c_law.setText("Law");

        c_history.setText("History");

        c_religion.setText("Religion/  Theology");

        c_other.setText("Other");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(53, 53, 53)
                .addComponent(jButton2)
                .addGap(123, 123, 123))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c_bidAll)
                    .addComponent(c_art)
                    .addComponent(c_computerScience)
                    .addComponent(c_engineering)
                    .addComponent(c_healthCare)
                    .addComponent(c_humanities)
                    .addComponent(c_marketing)
                    .addComponent(c_naturalScience)
                    .addComponent(c_politicalScience)
                    .addComponent(c_religion)
                    .addComponent(c_other))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c_businessManagement)
                    .addComponent(c_economics)
                    .addComponent(c_englishLiterature)
                    .addComponent(c_socialSciences)
                    .addComponent(c_psychology)
                    .addComponent(c_philosophy)
                    .addComponent(c_mathematicsStatistics)
                    .addComponent(c_law)
                    .addComponent(c_history))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(c_bidAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_art)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_computerScience)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_engineering)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_healthCare)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_humanities)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_marketing)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_naturalScience)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_politicalScience)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_religion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_other))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(c_businessManagement)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_economics)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_englishLiterature)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_history)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_law)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_mathematicsStatistics)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_philosophy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_psychology)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_socialSciences)))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Menu");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Home");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
          int[] selectedIndices = subjects.getSelectedIndices();
            String[] myArray = new String[50];
            for (int i = 0; i < selectedIndices.length; i++) {
                           myArray[i] =  String.valueOf(subjects.getModel().getElementAt(selectedIndices[i]));
                           System.out.println(myArray[i]);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void c_bidAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_bidAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_bidAllActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        
        dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void c_bidAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c_bidAllMouseClicked
        if(c_bidAll.isSelected()==false){
          
           c_art.setSelected(true);
           c_art.setEnabled(false);
           c_computerScience.setSelected(true);
           c_engineering.setSelected(true);
           c_healthCare.setSelected(true);
           c_humanities.setSelected(true);
           c_marketing.setSelected(true);
           c_naturalScience.setSelected(true);
           c_politicalScience.setSelected(true);
           c_businessManagement.setSelected(true);
           c_economics.setSelected(true);
           c_englishLiterature.setSelected(true);
           c_socialSciences.setSelected(true);
           c_psychology.setSelected(true);
           c_philosophy.setSelected(true);
           c_mathematicsStatistics.setSelected(true);
           c_law.setSelected(true);
           c_history.setSelected(true);
           c_religion.setSelected(true);
           c_other.setSelected(true);
//            String [] checkNames={"c_bidAll","c_art","c_computerScience","c_engineering","c_healthCare","c_humanities","c_marketing","c_naturalScience","c_politicalScience","c_businessManagement","c_economics","c_englishLiterature","c_socialSciences","c_psychology","c_philosophy","c_mathematicsStatistics","c_law","c_history","c_religion","c_other"};

        }else{
           c_art.setSelected(false);
           c_computerScience.setSelected(false);
           c_engineering.setSelected(false);
           c_healthCare.setSelected(false);
           c_humanities.setSelected(false);
           c_marketing.setSelected(false);
           c_naturalScience.setSelected(false);
           c_politicalScience.setSelected(false);
           c_businessManagement.setSelected(false);
           c_economics.setSelected(false);
           c_englishLiterature.setSelected(false);
           c_socialSciences.setSelected(false);
           c_psychology.setSelected(false);
           c_philosophy.setSelected(false);
           c_mathematicsStatistics.setSelected(false);
           c_law.setSelected(false);
           c_history.setSelected(false);
           c_religion.setSelected(false);
           c_other.setSelected(false);
        }
        
       
    }//GEN-LAST:event_c_bidAllMouseClicked

    private void c_artMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c_artMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_c_artMouseMoved

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox c_art;
    private javax.swing.JCheckBox c_bidAll;
    private javax.swing.JCheckBox c_businessManagement;
    private javax.swing.JCheckBox c_computerScience;
    private javax.swing.JCheckBox c_economics;
    private javax.swing.JCheckBox c_engineering;
    private javax.swing.JCheckBox c_englishLiterature;
    private javax.swing.JCheckBox c_healthCare;
    private javax.swing.JCheckBox c_history;
    private javax.swing.JCheckBox c_humanities;
    private javax.swing.JCheckBox c_law;
    private javax.swing.JCheckBox c_marketing;
    private javax.swing.JCheckBox c_mathematicsStatistics;
    private javax.swing.JCheckBox c_naturalScience;
    private javax.swing.JCheckBox c_other;
    private javax.swing.JCheckBox c_philosophy;
    private javax.swing.JCheckBox c_politicalScience;
    private javax.swing.JCheckBox c_psychology;
    private javax.swing.JCheckBox c_religion;
    private javax.swing.JCheckBox c_socialSciences;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane scroller;
    private javax.swing.JList<String> subjects;
    // End of variables declaration//GEN-END:variables
}
